### ISSUE TITLE
feat: 유저 타입 수정 api 

### ISSUE THREAD

**Issue by punchdrunkard** [dnd-side-project/dnd-11th-5-backend#172]
## TODO

- [ ] 유저 타입 수정 api 구현 
- [ ] 테스트 코드 작성
- [ ] 유저-(온보딩 체크 목록) 매핑 테이블의 유저 id 에 index 추가하기

## ETC
- 수정한거 저장하기 전에 **기존 정보 삭제** 필요
