### ISSUE TITLE
env : db 연동

### ISSUE THREAD

**Issue by punchdrunkard** [dnd-side-project/dnd-11th-5-backend#23]
## 개요

flyway 설정 및 운영 db 연동 

## TODO

- [ ] flyway 의존성 추가
- [ ] erd 바탕으로 script 작성
- [ ] 운영환경 db 연동

## ETC
참고자료
- https://www.blog.ecsimsw.com/entry/Flyway%EB%A1%9C-DB-Migration
- https://hudi.blog/dallog-flyway/
- https://kth990303.tistory.com/357
