### ISSUE TITLE
feat: 온보딩 정적 데이터 조회 api 구현

### ISSUE THREAD

**Issue by punchdrunkard** [dnd-side-project/dnd-11th-5-backend#28]
## 개요

온보딩에 사용되는 정적 데이터들을 조회하는 api를 구현합니다.

## TODO

- [ ] 엔티티 생성
- [ ] 조회 api 구현
  - [ ] 페스티벌 분위기 조회
  - [ ] 페스티벌 분야 조회
  - [ ] 페스티벌 일행 분류 조회
  - [ ] 페스티벌 우선 순위 분류 조회
